# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LifeGauge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LifeGauge
  pod 'R.swift'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'RxSwift'
  pod 'RxCocoa' 

  target 'LifeGaugeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LifeGaugeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
